name: ai_english
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  # Flutter本体。Flutterアプリケーションを構築するためのフレームワーク。
  flutter:
    sdk: flutter
  # Cupertinoデザインのアイコン集。iOS風のUIを提供するために使用。
  cupertino_icons: ^1.0.8
  # Freezedのアノテーション。イミュータブルなデータクラス生成を支援。
  freezed_annotation: ^2.4.4
  # JSONシリアライズ用のアノテーション。JSONとDart間の変換をサポート。
  json_annotation: ^4.9.0
  # ステート管理ライブラリ。宣言的な状態管理を実現するために利用。
  flutter_riverpod: ^2.6.1
  # Riverpod用のアノテーション。コード生成のための設定を補助。
  riverpod_annotation: ^2.6.1
  # HTTPクライアントライブラリ。API呼び出しやネットワーク通信を効率化。
  dio: ^5.8.0+1
  flutter_tts: ^4.2.2
  uuid: ^4.5.1
  flutter_spinkit: ^5.1.0
  # flutter_localizationsが0.19.0を要求しているため、明示的に指定。
  intl: 0.19.0
  flutter_localizations:
    sdk: flutter
  # Flutter Hooksライブラリ。フックを利用して状態管理を行うために使用。
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.5.2
  page_transition: ^2.2.1
  flutter_launcher_icons: ^0.14.3
  hooks_riverpod: ^2.6.1
  flutter_html: ^3.0.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.12.1

dev_dependencies:
  # Flutterのテストフレームワーク。単体テストやウィジェットテストの実行に使用。
  flutter_test:
    sdk: flutter
  # Flutter用のLinter。コーディング規約に沿ったコード作成をサポート。
  flutter_lints: ^5.0.0
  # コード生成を実行するためのツール。Freezedやjson_serializableなどと連携。
  build_runner: ^2.4.14
  # Freezedパッケージ本体。データクラスやユニオン型のコード生成を行う。
  freezed: ^2.5.8
  # JSONシリアライズ処理のコード生成ライブラリ。DartオブジェクトとJSON間の変換コードを自動生成。
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  # モック用のライブラリ。ユニットテストやウィジェットテストを実行するために使用。
  mockito: ^5.4.5

  # 自動生成ファイルの出力先を指定するためのツール。
  source_gen: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
