// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4SmZqa9OqOsZhqwp-Ew5IXywvPmRZQo',
    appId: '1:149293681507:web:92804ea748ea091a826156',
    messagingSenderId: '149293681507',
    projectId: 'eigoat',
    authDomain: 'eigoat.firebaseapp.com',
    storageBucket: 'eigoat.firebasestorage.app',
    measurementId: 'G-C1C2ST249L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBunRkIEMamo7ZyZstujRMBDjolAP_Du0w',
    appId: '1:149293681507:ios:c9fdcfa892ba2187826156',
    messagingSenderId: '149293681507',
    projectId: 'eigoat',
    storageBucket: 'eigoat.firebasestorage.app',
    iosBundleId: 'com.example.aiEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU4SmZqa9OqOsZhqwp-Ew5IXywvPmRZQo',
    appId: '1:149293681507:web:1bce996e953cbeb0826156',
    messagingSenderId: '149293681507',
    projectId: 'eigoat',
    authDomain: 'eigoat.firebaseapp.com',
    storageBucket: 'eigoat.firebasestorage.app',
    measurementId: 'G-HM4T3FZKQX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBunRkIEMamo7ZyZstujRMBDjolAP_Du0w',
    appId: '1:149293681507:ios:c9fdcfa892ba2187826156',
    messagingSenderId: '149293681507',
    projectId: 'eigoat',
    storageBucket: 'eigoat.firebasestorage.app',
    iosBundleId: 'com.example.aiEnglish',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsaxXc3gezvnRwwFgowRdxbHVSVsQ97ms',
    appId: '1:149293681507:android:9e1c6c63cd534f15826156',
    messagingSenderId: '149293681507',
    projectId: 'eigoat',
    storageBucket: 'eigoat.firebasestorage.app',
  );

}